#! /usr/bin/env sh

ROOT=$(cd $(dirname $0); pwd -P)

for dirname in $ROOT/*; do
  if [ -d $dirname ]; then
    echo "linking $dirname"
    ln -sf $dirname ~
  fi
done

for filename in $ROOT/.*; do
  if [ -f $filename ]; then
    echo "linking $filename"
    ln -f $filename ~
  fi
done
