#! /usr/bin/env sh

ROOT=$(cd $(dirname $0); pwd -P)

for dirname in $ROOT/*; do
  if [ -d $dirname ]; then
    echo "linking $dirname"
    ln -shf $dirname ~/.$(basename $dirname)
  fi
done


for filename in\
  $ROOT/gemrc\
  $ROOT/gitconfig\
  $ROOT/gitignore\
  $ROOT/gvimrc.after\
  $ROOT/irbrc\
  $ROOT/pryrc\
  $ROOT/railsrc\
  $ROOT/screenrc\
  $ROOT/vimrc.after\
  $ROOT/vimrc.before\
  $ROOT/zshrc
do
  if [ -f $filename ]; then
    echo "linking $filename"
    ln -f $filename ~/.$(basename $filename)
  fi
done
