#! /usr/bin/env zsh

export NOTES_ROOT=~/Dropbox/Notes

# Create a new note.
note(){
  local DIR="$NOTES_ROOT/$(date +%Y)/$(date +%m)/$(date +%d)"
  mkdir -p $DIR
  $EDITOR "$DIR/$(date +%T).txt"
}

# Review Notes
notes(){
  # Display notes reverse cronigically
  local OUTPUT=$(mktemp -t notes)
  for file in $(find $NOTES_ROOT -type f | sort -r); do
    echo "\n=== $file ===\n" >> $OUTPUT
    cat $file >> $OUTPUT
    echo "\n" >> $OUTPUT
  done
  cat $OUTPUT | less
  rm $OUTPUT
}



